website/auth.py
from flask import Blueprint, render_template, request, jsonify, flash, redirect, url_for
from .models import User, Attraction, HotelReservation, Cart, CartAttraction, Booking, CardDetails
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user
from .forms import CheckoutForm, EditBookingForm

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
  background_class = 'body-login'
  if request.method == 'POST':
     email = request.form.get('email') # gets the email from the database
     password = request.form.get('password') # gets the password from the database

     user = User.query.filter_by(email=email).first()
     if user:
        if check_password_hash(user.password, password):
           flash('Logged in successfully!', category='success')
           login_user(user, remember=True)
           return redirect(url_for('views.home'))
        else:
           flash('Incorrect password, try again.', category='error')
     else:
       flash('Email does not exist.', category='error')
      
  return render_template("login.html", background_class=background_class)

@auth.route('/logout')
@login_required
def logout():
   logout_user()
   return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    background_class = 'body-sign-up'
    if request.method == 'POST':
        firstname = request.form.get('firstname').strip()
        lastname = request.form.get('lastname').strip()
        email = request.form.get('email').strip()
        password = request.form.get('password').strip()
        confirmpassword = request.form.get('confirmpassword').strip()

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(firstname) < 2:
            flash('First Name must be greater than 2 characters.', category='error')
        elif len(lastname) < 2:
            flash('Last Name must be greater than 2 characters.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 4 characters.', category='error')
        elif len(password) <= 7:
            flash('Password must be greater than 7 characters.', category='error')
        elif confirmpassword != password:
            flash('Passwords do not match.', category='error')
        else:
            new_user = User(first_name=firstname, last_name=lastname, email=email, password=generate_password_hash(password))
            
            # this logic grants customers with a free guided tour when signing up
            new_user.has_free_tour = True
            
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign-up.html", background_class=background_class)


@auth.route('/forgot-password', methods=['GET', 'POST'])
def forgot_password():
    background_class = 'body-forgot-password'
    if request.method == 'POST':
        email = request.form.get('email')
        if email:
            email = email

            user = User.query.filter_by(email=email).first()
            if user:
                new_password = request.form.get('new_password')
                confirm_password = request.form.get('confirm_password')

                if new_password != confirm_password:
                    flash('Passwords do not match.', category='error')
                elif len(new_password) <= 7:
                    flash('Password must be greater than 7 characters.', category='error')
                else:
                    # Update user's password
                    user.password = generate_password_hash(new_password)
                    db.session.commit()

                    flash('Password reset successfully!', category='success')
                    return redirect(url_for('auth.login'))
            else:
                flash('Email does not exist.', category='error')
        else:
            flash('Email field is required.', category='error')

    return render_template("forgot-password.html", background_class=background_class)

@auth.route('/base')
def base2():
   return render_template("base.html")

@auth.route('/base2')
def base():
   return render_template("base2.html")

@auth.route('/discovery-cart-tour')
def discovery_cart_tour():
    background_class = 'body-discovery-cart-tour' #sets a background class for this page
    # This gets the attraction from the database
    attraction = Attraction.query.filter_by(name='Discovery Cart Tour').first()
    return render_template("discovery-cart-tour.html", background_class=background_class, attraction=attraction)

@auth.route('/animals-in-action')
def animals_in_action():
   background_class = 'body-animals-in-action' 
   attraction = Attraction.query.filter_by(name='Animals in Action').first()
   return render_template("animals-in-action.html", background_class=background_class)

@auth.route('/australian-outback-adventure')
def autralian_outback_adventure():
   background_class = 'body-australian-outback-adventure'
   attraction = Attraction.query.filter_by(name='Australian Outback Adventure').first()
   return render_template("australian-outback-adventure.html", background_class=background_class) 

@auth.route('/safari-trail')
def safari_trail():
   background_class = 'body-safari-trail'
   attraction = Attraction.query.filter_by(name='Safari Trail').first()
   return render_template("safari-trail.html", background_class=background_class)

@auth.route('/childrens-zoo')
def childrens_zoo():
   background_class = 'body-childrens-zoo'
   attraction = Attraction.query.filter_by(name='Childrens Zoo').first()
   return render_template("childrens-zoo.html", background_class=background_class)                

@auth.route('/exclusive-experiences')
def exclusive_experiences():
   background_class = 'body-exclusive-experiences'
   attraction = Attraction.query.filter_by(name='Exclusive Experiences').first()
   return render_template("exclusive-experiences.html", background_class=background_class)

@auth.route('/education')
def education():
   background_class = 'body-education'
   return render_template("education.html", background_class=background_class)

@auth.route('/guided-tours')
def guided_tours():
   background_class = 'body-guided-tours'
   attraction = Attraction.query.filter_by(name='Guided Tours').first()
   return render_template("guided-tours.html", background_class=background_class)

@auth.route('/help-center')
def help_center():
   background_class = 'body-help-center'
   return render_template("help-center.html", background_class=background_class)

@auth.route('/materials')
def materials():
   background_class = 'body-materials'
   return render_template("materials.html", background_class=background_class)

@auth.route('/plan-your-stay')
def plan_your_stay():
   background_class = 'body-plan-your-stay'
   return render_template("plan-your-stay.html", background_class=background_class)

@auth.route('/plan-your-visit')
def plan_your_visit():
   background_class = 'body-plan-your-visit'
   return render_template("plan-your-visit.html", background_class=background_class)

@auth.route('/rewards')
def rewards():
   background_class = 'body-rewards'
   return render_template("rewards.html", background_class=background_class)

@auth.route('/school-groups')
def school_groups():
   background_class = 'body-school-groups'
   return render_template("school-groups.html", background_class=background_class)

@auth.route('/things-to-do')
def things_to_do():
   background_class = 'body-things-to-do'
   return render_template("things-to-do.html", background_class=background_class)

@auth.route('/wildlife')
def wildlife():
   background_class = 'body-wildlife'
   return render_template("wildlife.html", background_class=background_class)

@auth.route('/my-cart')
@login_required
def my_cart():
    background_class = 'body-my-cart'
    cart = current_user.cart
    if cart:
        cart_items = [(attraction, cart.quantity, cart.price) for attraction in cart.attractions]
        return render_template("my-cart.html", background_class=background_class, cart_items=cart_items)
    else:
        flash('Cart is empty!', category='info')
        return redirect(url_for('views.home'))

@auth.route('/add-to-cart/<int:attraction_id>')
@login_required
def add_to_cart(attraction_id):
    attraction = Attraction.query.get(attraction_id)
    if attraction:
        cart = current_user.cart
        if not cart:
            cart = Cart(user_id=current_user.id)
            db.session.add(cart)

        quantity = request.args.get('quantity', type=int, default=1)  # Get quantity from query parameters
        if quantity < 1:
            flash('Invalid quantity.', category='error')
            return redirect(url_for('views.home'))

        cart_item = CartAttraction.query.filter_by(cart_id=cart.id, attraction_id=attraction.id).first()
        if not cart_item:
            cart_item = CartAttraction(cart_id=cart.id, attraction_id=attraction.id, quantity=quantity, price=attraction.price)
            db.session.add(cart_item)
        else:
            cart_item.quantity += quantity

        db.session.commit()
        flash('Attraction added to cart successfully!', category='success')
        return redirect(url_for('auth.my_cart'))
    else:
        flash('Attraction not found!', category='error')
        return redirect(url_for('views.home'))
    
@auth.route('/increase-quantity/<int:cart_item_id>')
@login_required
def increase_quantity(cart_item_id):
    cart_item = CartAttraction.query.get_or_404(cart_item_id)
    cart_item.quantity += 1
    db.session.commit()
    flash('Quantity increased!', category='success')

website/templates/animals-in-action.html
{% extends "base.html" %}

{% block title %}Animals in Action{% endblock %}

{% block header %}
<div class="header-container">
  <header class="header">
    <h1>Animals in Action</h1>
  </header>
</div>
{% endblock %}

{% block content%}

<style>
  .age-info img, .ticket-info img, .time-info img, .availability-info img {
    width: 25%;
  }
</style>

<div class="attraction-container">
  <div class="attraction-left-container">
    <div class="attraction-header">£20 & over</div>
    <div class="availability-calendar-section">
      <div id="availability-calendar"></div>
    </div>
    <div class="availability-date-section">
      <div id="selected-date"></div>
    </div>
    <div class="book-now-button">
      <a href="{{ url_for('auth.add_to_cart', attraction_id=attraction.id) }}" class="book-now">Book Now</a>
    </div>
    <p class="price-per-person">*Price is per person.</p>
  </div>
  <div class="attraction-right-container">
    <div class="attraction-header">Animals in Action</div>
    <div class="attraction-details-section">
      <p>Experience the thrill of our Animals in Action shows, where our talented trainers showcase the amazing abilities and natural behaviors of our animal ambassadors. From breathtaking aerial displays to jaw-dropping feats of agility, witness the extraordinary skills of our animal stars up close. Join us for an unforgettable adventure filled with excitement, education, and plenty of fun for the whole family!</p>
      <div class="attraction-details">
        <div class="age-info">
          <img src="../static/images/people-icon.jpg">
          <span>For all ages</span>
        </div><br>
        <div class="ticket-info">
          <img src="../static/images/ticket.png">
          <span>£20 & over</span>
        </div><br>
        <div class="time-info">
          <img src="../static/images/time.jpg">
          <span>3.5 hours&nbsp&nbsp</span>
        </div><br>
        <div class="availability-info">
          <img src="../static/images/calendar.jpg">
          <span>Everyday&nbsp&nbsp</span>
        </div><br>
      </div>
    </div>
  </div>
</div>


{% endblock %}

{% block js %}<script src="{{ url_for('static', filename='js/script.js') }}"></script>{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="static/CSS/body.css">
  <link rel="stylesheet" href="static/CSS/style.css">
  <link rel="stylesheet" href="static/CSS/main.css">
  <link rel="stylesheet" href="static/CSS/banner.css">
  <link rel="stylesheet" href="static/CSS/form.css">
  <link rel="stylesheet" href="static/CSS/messages.css">
  <link rel="stylesheet" href="static/CSS/scale.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

  <title>{% block title %}{% endblock %}</title>
</head>

<body class="{{ background_class }}">
  <div class="background-image">

    {% block header %}
      {% block header_button %}{% endblock %}
    {% endblock %}

    <div class="navbar-container">
      <nav class="navbar">
    
        <div class="logo">
            <a href="/Riget-Zoo-Adventures" class="company-logo">Riget Zoo Adventures</a>
        </div>
        <ul class="menu">
            <li><a href="/plan-your-visit">Visit</a>
                <ul class="submenu">
                    <li><a href="/rewards">Rewards</a></li>
                    <li><a href="/plan-your-visit">Plan Your Visit</a></li>
                    <li><a href="/plan-your-stay">Plan Your Stay</a></li>
                </ul>
            </li>
            <li><a href="/wildlife">Wildlife</a></li>
            <li><a href="/things-to-do">Things to Do</a>
                <ul class="submenu">
                    <li><a href="/Riget-Zoo-Adventures">Attractions</a></li>
                    <li><a href="/exclusive-experiences">Exclusive Experiences</a></li>
                </ul>
            </li>
            <li><a href="/education">Education</a>
                <ul class="submenu">
                    <li><a href="/guided-tours">Guided Tours</a></li>
                    <li><a href="/materials">Materials</a></li>
                    <li><a href="/school-groups">School Groups</a></li>
                </ul>
            </li>
        </ul>
        <div class="info">
          <div class="left-section">
            <a href="help-center" class="help-center">Help Center</a>
            <span class="separator">|</span>
            <img src="static/images/accessibility.jpg" alt="Accessibility" class="accessibility-icon">
            <a href="/login" class="account">Account</a>
          </div>
          <div class="right-section">
            <a href="/rewards">
              <button class="offers">Offers</button>
            </a>
            <a href="/bookings">
              <button class="bookings">Bookings</button>
            </a>
          </div>
        </div>

      </nav>
    </div>

{% block error_message %}
  {% with messages = get_flashed_messages(with_categories=true) %} 
    {% if messages %}
      {% for category, message in messages %}
        {% if category == 'error' %}
          <div class="error-message" role="alert">
            {{ message }}
            <button type="button" class="close-button" onclick="this.parentElement.style.display='none';">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% else %}
          <div class="success-message" role="alert">
            {{ message }}
            <button type="button" class="close-button" onclick="this.parentElement.style.display='none';">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endif%}
      {% endfor %}
    {% endif %}
  {% endwith %}
{% endblock %}

    {% block form %}
    <div class="form-container">
      {% block form_content %}{% endblock %}    
    </div>
    {% endblock %} 

  </div>
  
  {% block content %}{% endblock %}

  <footer class="footer">
    <a href="/Riget-Zoo-Adventures" class="footer-logo">Riget Zoo Adventures</a>
    <div class="footer-container">
      <div class="footer-content">
        <div class="footer-column">
            <h3>About Us</h3>
            <p>About the Zoo</p>
            <p>Contact Us</p>
            <p>Careers</p>
        </div>
        <div class="footer-column">
            <h3>Visit Us</h3>
            <p>Location</p>
            <p>Hours & Tickets</p>
            <p>Attractions</p>
        </div>
        <div class="footer-column">
            <h3>Information</h3>
            <p>FAQs</p>
            <p>Privacy Policy</p>
            <p>Terms of Service</p>
        </div>
      </div>
      <div class="footer-bottom">
        <p>&copy; 2024 Riget Zoo Adventures. All rights reserved.</p>
      </div>
    </div>
</footer>

  {% block js %}{% endblock %}

</body>

</html>

website/templates/childrens-zoo.html
{% extends "base.html" %}

{% block title %}Childrens Zoo{% endblock %}

{% block header %}
<div class="header-container">
  <header class="header">
    <h1>Childrens Zoo</h1>
  </header>
</div>
{% endblock %}

{% block content %}

<style>
  .age-info img, .ticket-info img, .time-info img, .availability-info img {
    width: 25%;
  }
</style>

<div class="attraction-container">
  <div class="attraction-left-container">
    <div class="attraction-header">£15 & over</div>
    <div class="availability-calendar-section">
      <div id="availability-calendar"></div>
    </div>
    <div class="availability-date-section">
      <div id="selected-date"></div>
    </div>
    <div class="book-now-button">
      <a href="{{ url_for('auth.add_to_cart', attraction_id=attraction.id) }}" class="book-now">Book Now</a>
    </div>
    <p class="price-per-person">*Price is per person.</p>
  </div>
  <div class="attraction-right-container">
    <div class="attraction-header">Childrens Zoo</div>
    <div class="attraction-details-section">
      <p>Step into a world of wonder at our Children's Zoo, where young explorers can engage with friendly animals and interactive exhibits designed just for them! From cuddly farm animals to exotic creatures from around the globe, kids can enjoy hands-on encounters, educational activities, and playful adventures. Watch as their faces light up with joy as they pet a fluffy bunny, feed gentle goats, or marvel at colorful birds. With special areas for learning and discovery, our Children's Zoo is the perfect place for kids to connect with nature.</p>
      <div class="attraction-details">
        <div class="age-info">
          <img src="../static/images/people-icon.jpg">
          <span>For all ages</span>
        </div><br>
        <div class="ticket-info">
          <img src="../static/images/ticket.png">
          <span>£15 & over</span>
        </div><br>
        <div class="time-info">
          <img src="../static/images/time.jpg">
          <span>3.5 hours&nbsp&nbsp</span>
        </div><br>
        <div class="availability-info">
          <img src="../static/images/calendar.jpg">
          <span>Everyday&nbsp&nbsp</span>
        </div><br>
      </div>
    </div>
  </div>
</div>


{% endblock %}

{% block js %}<script src="{{ url_for('static', filename='js/script.js') }}"></script>{% endblock %}

website/templates/exclusive-experiences.html
{% extends "base.html" %}

{% block title %}Exclusive Experiences{% endblock %}

{% block header %}
<div class="header-container">
  <header class="header">
    <h1>Exclusive Experiences</h1>
  </header>
</div>
{% endblock %}

{% block content%}

<style>
  .age-info img, .ticket-info img, .time-info img, .availability-info img {
    width: 25%;
    margin-top: 0;
  }
  .attraction-details {
    margin-top: 13vh;
  }
  .attraction-details-section p {
    font-size: 18px;
  }
  .attraction-header {
    color: red;
    text-decoration: underline;
  }
</style>

<div class="attraction-container">
  <div class="attraction-left-container">
    <div class="attraction-header">£170 & over</div>
    <div class="availability-calendar-section">
      <div id="availability-calendar"></div>
    </div>
    <div class="availability-date-section">
      <div id="selected-date"></div>
    </div>
    <div class="book-now-button">
      <a href="{{ url_for('auth.add_to_cart', attraction_id=attraction.id) }}" class="book-now">Book Now</a>
    </div>
    <p class="price-per-person">*Price is per person.</p>
  </div>
  <div class="attraction-right-container">
    <div class="attraction-header">Exclusive Experiences (VIP)</div>
    <div class="attraction-details-section">
      <p>Indulge in unforgettable moments with our Exclusive Experiences, where you can elevate your zoo visit to new heights of luxury and excitement. Whether you're seeking a personalized tour with our expert guides, a behind-the-scenes peek into animal care and conservation efforts, or a private encounter with your favorite creatures, our Exclusive Experiences offer something extraordinary for every animal lover. Treat yourself to VIP treatment as you enjoy exclusive access to restricted areas, intimate animal encounters, and tailor-made adventures designed to fulfill your wildest dreams. Whether you're celebrating a special occasion or simply seeking a one-of-a-kind adventure, our Exclusive Experiences promise to create memories that will last a lifetime. Join us for an unforgettable journey into the heart of the wild, where extraordinary moments await around every corner!</p>
      <div class="attraction-details">
        <div class="age-info">
          <img src="../static/images/people-icon.jpg">
          <span>For all ages</span>
        </div><br>
        <div class="ticket-info">
          <img src="../static/images/ticket.png">
          <span>£170 & over</span>
        </div><br>
        <div class="time-info">
          <img src="../static/images/time.jpg">
          <span>3.5 hours&nbsp&nbsp</span>
        </div><br>
        <div class="availability-info">
          <img src="../static/images/calendar.jpg">
          <span>Everyday&nbsp&nbsp</span>
        </div><br>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block js %}<script src="{{ url_for('static', filename='js/script.js') }}"></script>{% endblock %}

website/templates/guided-tours.html
{% extends "base.html" %}

{% block title %}Guided Tours{% endblock %}

{% block header %}
<div class="header-container">
  <header class="header">
    <h1>Guided Tours</h1>
  </header>
</div>
{% endblock %}

{% block content %}

<style>
  .age-info img, .ticket-info img, .time-info img, .availability-info img {
    width: 25%;
  }
  .attraction-details {
    margin-top: 8vh;
  }
</style>

<div class="attraction-container">
  <div class="attraction-left-container">
    <div class="attraction-header">£42 & over</div>
    <div class="availability-calendar-section">
      <div id="availability-calendar"></div>
    </div>
    <div class="availability-date-section">
      <div id="selected-date"></div>
    </div>
    <div class="book-now-button">
      <a href="{{ url_for('auth.add_to_cart', attraction_id=attraction.id) }}" class="book-now">Book Now</a>
    </div>
    <p class="price-per-person">*Price is per person.</p>
  </div>
  <div class="attraction-right-container">
    <div class="attraction-header">Guided Tours</div>
    <div class="attraction-details-section">
      <ul>
        <li><b>Engaging and Informative Tours:</b> Led by knowledgeable guides, our tours offer interactive experiences filled with fascinating facts and insights about wildlife.</li>
        <li><b>Explore Diverse Habitats:</b> Journey through various habitats, encountering a wide range of animal species from around the world.</li>
        <li><b>Up Close with Incredible Wildlife:</b> Get close to majestic animals like giraffes and cheetahs, creating unforgettable memories.</li>
        <li><b>Conservation Highlights:</b> Learn about our conservation efforts to protect endangered species and their habitats.</li>
        <li><b>Perfect for All Ages:</b> Whether with family, school groups, or wildlife enthusiasts, our tours cater to everyone's interests and needs.</li>
      </ul>
      <div class="attraction-details">
        <div class="age-info">
          <img src="../static/images/people-icon.jpg">
          <span>For all ages</span>
        </div><br>
        <div class="ticket-info">
          <img src="../static/images/ticket.png">
          <span>£42 & over</span>
        </div><br>
        <div class="time-info">
          <img src="../static/images/time.jpg">
          <span>3.5 hours&nbsp&nbsp</span>
        </div><br>
        <div class="availability-info">
          <img src="../static/images/calendar.jpg">
          <span>Everyday&nbsp&nbsp</span>
        </div><br>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block js %}<script src="{{ url_for('static', filename='js/script.js') }}"></script>{% endblock %}

website/templates/plan-your-stay.html
{% extends "base.html" %}

{% block title %}Plan Your Stay{% endblock %}

{% block header %}
<div class="header-container">
  <header class="header">
    <h1>Plan Your Stay</h1>
  </header>
</div>
{% endblock %}

{% block content%}

<style>
  .attraction-details-section li {
    text-align: center;
    list-style-type: none;
    color: white;
    background-color: rgba(0, 0, 0, 0.6); 
    border-radius: 10px;
  }
  .attraction-right-container {
    background-image: url(../static/images/plan_your_stay2.jpeg);
  }
  .book-now-button {
    margin-top: 5vh;
  }
</style>

<div class="attraction-container">
  <div class="attraction-left-container">
    <div class="attraction-header">£110 & over</div>
    <div class="availability-section">
      <h2>Check Availability</h2>
      <div class="input-availability-container">
        <label for="check-in">Check-in:</label>
        <input type="date" id="check-in" name="check-in" min="2024-06-01" max="2025-12-31">
      </div>
      <div class="input-availability-container">
        <label for="check-out">Check-out:</label>
        <input type="date" id="check-out" name="check-out" min="2024-06-01" max="2025-12-31">
      </div>
      <div class="input-quantity-container">
        <label for="rooms">Rooms:</label>
        <select id="rooms" name="rooms">
          <option value="1">1</option> <option value="2">2</option> <option value="3">3</option> <option value="4">4</option> <option value="5">5</option>
        </select>
      </div>
      <div class="input-quantity-container">
        <label for="adults">Adults:</label>
        <select id="adults" name="adults"><option value="1">1</option> <option value="2">2</option> <option value="3">3</option> <option value="4">4</option> <option value="5">5</option>
        </select>
      </div>
      <div class="input-quantity-container" >
        <label for="children">Children:</label>
        <select id="children" name="children">
          <option value="0">0</option> <option value="1">1</option> <option value="2">2</option> <option value="3">3</option> <option value="4">4</option> <option value="5">5</option>
        </select>
      </div>
      <div class="book-now-button">
        <a href="{{ url_for('auth.add_to_cart', attraction_id=attraction.id) }}" class="book-now">Book Now</a>
      </div>
    </div>
  </div>
  <div class="attraction-right-container">
    <div class="attraction-header" style="color: white;">Book a Stay at our On-site Hotel</div>
    <div class="attraction-details-section">
      <ul>
        <li><b>Accommodation Options:</b> <br> Choose from a variety of rooms and suites designed to cater to different preferences and group sizes. Whether you're traveling solo, with family, or friends, we have the perfect room for you.</li>
        <li><b>Amenities:</b> <br> Enjoy complimentary breakfast, free Wi-Fi, access to zoo attractions, a swimming pool, fitness center, and delicious dining options available right at your doorstep.</li>
        <li><b>Wildlife Encounters:</b> <br> As a guest of our hotel, you'll have the exclusive opportunity to participate in special tours and animal encounters led by our expert guides. Get up close and personal with some of the world's most incredible wildlife.</li>
        <li><b>Information:</b> <br> Ready to book your stay? Visit our website or contact us directly to make a reservation. We look forward to welcoming you to our riget zoo hotel!</li>
        <li><b>Pricing:</b> <br> Starting from £110 per night, our room rates offer excellent value for money. Take advantage of our special offers and packages to make the most of your stay.</li>
      </ul>
    </div>
  </div>
</div>


{% endblock %}

website/templates/safari-trail.html
{% extends "base.html" %}

{% block title %}Safari Trail{% endblock %}

{% block header %}
<div class="header-container">
  <header class="header">
    <h1>Safari Trail</h1>
  </header>
</div>
{% endblock %}

{% block content%}

<style>
  .age-info img, .ticket-info img, .time-info img, .availability-info img {
    width: 25%;
  }
</style>

<div class="attraction-container">
  <div class="attraction-left-container">
    <div class="attraction-header">£35 & over</div>
    <div class="availability-calendar-section">
      <div id="availability-calendar"></div>
    </div>
    <div class="availability-date-section">
      <div id="selected-date"></div>
    </div>
    <div class="book-now-button">
      <a href="{{ url_for('auth.add_to_cart', attraction_id=attraction.id) }}" class="book-now">Book Now</a>
    </div>
    <p class="price-per-person">*Price is per person.</p>
  </div>
  <div class="attraction-right-container">
    <div class="attraction-header">Safari Trail</div>
    <div class="attraction-details-section">
      <p>Explore the untamed wilderness of Africa right in the heart of our zoo! Our Safari Trail offers an exhilarating adventure where you can encounter majestic lions, graceful giraffes, playful elephants, and a host of other awe-inspiring wildlife species. Traverse through lush savannahs, dense jungles, and tranquil watering holes as you immerse yourself in the sights and sounds of the African wilderness. Our Safari Trail promises an unforgettable journey into the heart of Africa's natural wonders.</p>
      <div class="attraction-details">
        <div class="age-info">
          <img src="../static/images/people-icon.jpg">
          <span>For all ages</span>
        </div><br>
        <div class="ticket-info">
          <img src="../static/images/ticket.png">
          <span>£35 & over</span>
        </div><br>
        <div class="time-info">
          <img src="../static/images/time.jpg">
          <span>3.5 hours&nbsp&nbsp</span>
        </div><br>
        <div class="availability-info">
          <img src="../static/images/calendar.jpg">
          <span>Everyday&nbsp&nbsp</span>
        </div><br>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block js %}<script src="{{ url_for('static', filename='js/script.js') }}"></script>{% endblock %}